version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: winston-logger-wrapper
 
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Run logger
          command: |
            node -v
            node src\logger.js
