version: 2.1

orbs:
  jq: circleci/jq@2.2.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-browsers
  shell: /bin/bash

workflows:
  build-test-and-publish:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - publish:
      #     context:
      #       - winston-logger-wrapper-variables
      #     requires:
      #       - test
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - jq/install
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Update yarn
          command: "curl -o- -L https://yarnpkg.com/install.sh | bash"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: |
            yarn install --modules-folder dist/node_modules/
      - run:
          name: Run build
          command: |
            yarn build
            cat dist/package.json
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  # test:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run:
  #         name: Run tests
  #         command: yarn --cwd publish test
  # publish:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run:
  #         name: Authenticate with registry
  #         command: |
  #           echo "$NPM_TOKEN"
  #           echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/publish/.npmrc
  #     - run:
  #         name: Publish package
  #         command: |
  #           cd publish/
  #           npm publish
