version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-browsers

workflows:
  build-test-and-publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          context:
           - winston-logger-wrapper-variables
          requires:
            - test
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: npm test
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: |
            echo "$NPM_TOKEN"
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
       - run:
          name: Publish package
          command: npm publish
      
      
    
          
